### PR TITLE
add url_suffix

### PR DESCRIPTION
**Pull request by pawrequest**
add optional url_suffix attr to FlaskUI class

if present url_suffix is appended to self.url before launch

### CODE REVIEW

**Comment by ClimenteA** [comment]
Here you could use the `redirect` functionality in the web framework you picked.

- https://flask.palletsprojects.com/en/2.3.x/api/#flask.redirect
- https://fastapi.tiangolo.com/advanced/custom-response/#redirectresponse

**Comment by pawrequest** [comment]
hi, sorry i don't really understand how to use a dynamically defined redirect with flaskwebgui - can you help? 

i can hardcode a redirect target into the root endpoint, but how do i do it dynamically?
 
i do not know the url i want to load until runtime as it is dependent on a sqlmodel database call returning an ID.

if i can't work out the approved method (and assuming you wont reconsider the url_suffix pr) i'll keep using my fork - are there any negative implications to this naive approach? 

```
@dataclass
class FlaskUI:
    ....
    url_suffix: str = None
    ...

    def __post_init__(self):
        ...
        base_url = f"http://127.0.0.1:{self.port}"
        self.url = f"{base_url}/{self.url_suffix}" if self.url_suffix else base_url
```

it allows the following usage which i find pretty intuitive:
```
    suffix = SOME_URL  

    fui = FlaskUI(
        app=app_file.app,
        server='fastapi',
        url_suffix=suffix
        )
        fui.run()
 ```

thanks a lot - i really appreciate your work!

**Comment by ClimenteA** [comment]
https://stackoverflow.com/questions/18967441/add-a-prefix-to-all-flask-routes

**Comment by pawrequest** [comment]
I'm using Fastapi, and don't want to prefix every route just change the first one...

Anyway, are there any gotchas with my naive url_suffix approach? as it seems to work as far as I can tell and I'm happy enough using my fork.

**Comment by ClimenteA** [comment]
All websites must have a root URL: (example.com, google.com). If they have something like google.com/some-route that was a redirect made in the web framework or load balancer.

If that works for you, go with what you know. 
Good luck!

**Comment by pawrequest** [comment]
Does fwg reference self.url for anything other than the initial page launch?

If so what? I.e are there unforseen consequences to my edit?

**Pull request closed without merging**
