### PR TITLE
Chrome management

### PR DESCRIPTION
**Pull request by alicjamusial**
A bit of hacky fix for issues: #2 and #9 

@ClimenteA please verify if it makes sense. And if it works on linux :)

**Breaking changes**
- two "virtual" application modes that can be called something like development and production modes - development mode is "by default" used when `browser_path` parameter is not defined (so it just opens the default browser). It still closes all Chrome running instances - because of Chromium's processes management restrictions, it's impossible to know which PIDs are ours. Sorry, I'm pretty sure, this is impossible.
- But! Placing a portable Chromium exe somewhere in the app and then defining `browser_path` parameter (let's call that "production mode") allows us to determine which processes are ours (wohoo!) and without closing any opened Chrome windows, makes it possible to detect if the appropiate window was closed (fixing #9).
- I get rid of the "feature" of "automatic detection" of Chromium exe in the folder - when we have any other `sh` or `exe` file in the structure (like the one in `dist` after using `pyvan` for example), it doesn't work at all, so it's misleading. In my humble opinion it's just better to define the `browser_path` explicitly :).

**Tested**
Tested on Windows 7 and 10, works fine. Tests on Linux needed.

**Current behaviour in short**
- no `browser_path` defined - "development mode" - Chrome open windows are closed to be able to determine PIDs correctly
- `browser_path` defined (and it's a separate browser file that normal OS browser!, e.g. portable Chromium exe)- "production mode" - we don't touch opened Chrome windows

### CODE REVIEW

**Comment by ClimenteA** [comment]
Awesome! :)

**Comment by ClimenteA** [comment]
Specified browser path on a downloaded portable chromium unfortunately  the server was still running after I closed flaskwebgui window.. (windows 10)

**Comment by alicjamusial** [comment]
> 
> 
> Specified browser path on a downloaded portable chromium unfortunately the server was still running after I closed flaskwebgui window.. (windows 10)

Hmm... So it looks like something could be wrong with fragment:
`len(list(filter(lambda p : 'chrome' in p.name() and p.cwd() == self.absolute_browser_directory, psutil.process_iter())))` - it should return 0 if the windows was closed. It's kind of interesting, because it would mean that this one process connected to your portable Chromium `cwd()` stayed open in your case... 
And did you try to test on Linux?

**Comment by ClimenteA** [comment]
The version I downloaded didn't had bin folder that was the issue.

**Comment by ClimenteA** [comment]
For linux things will be a little bit more complicated
Each version of linux installs chromium using different commands.
Bellow is for ubuntu:
```
sudo add-apt-repository ppa:canonical-chromium-builds/stage
sudo apt update
sudo apt install chromium-browser
```

**Pull request merged**
